<?php
return [
    'site_name' => 'bulletinbored',
    'home' => 'Startseite',
    'login' => 'Anmelden',
    'logout' => 'Abmelden',
    'register' => 'Registrieren',
    'username' => 'Benutzername',
    'password' => 'Passwort',
    'email' => 'E-Mail',
    'new_thread' => 'Neues Thema',
    'create_thread' => 'Neues Thema erstellen',
    'reply' => 'Antworten',
    'submit_reply' => 'Antwort senden',
    'edit_profile' => 'Profil bearbeiten',
    'save_changes' => 'Änderungen speichern',
    'profile' => 'Profil',
    'joined' => 'Beigetreten',
    'threads_by' => 'Themen von',
    'no_threads' => 'Noch keine Themen.',
    'no_replies' => 'Noch keine Antworten.',
    'login_required' => 'Anmeldung erforderlich',
    'invalid_credentials' => 'Ungültige Anmeldedaten',
    'welcome' => 'Willkommen',
    'password_reset_request' => 'Passwort-Reset-Anfrage',
    'password_reset_success' => 'Passwort-Reset erfolgreich',
    'search' => 'Suche',
    'categories' => 'Kategorien',
    'recent_threads' => 'Aktuelle Themen',
    'category' => 'Kategorie',
    'admin_panel' => 'Admin-Bereich',
    'admin_required' => 'Administrator erforderlich',
    'settings_saved' => 'Einstellungen erfolgreich gespeichert',
    'thread_not_found' => 'Thema nicht gefunden',
    'post_not_found' => 'Beitrag nicht gefunden',
    'delete_confirm' => 'Löschen?',
    'cancel' => 'Abbrechen',
    'attachments' => 'Anhänge',
    'optional' => 'Optional',
    'leave_blank_keep' => 'Leer lassen, um aktuellen Wert beizubehalten',
    'title' => 'Titel',
    'content' => 'Inhalt',
    'created_at' => 'Erstellt am',
    'updated_at' => 'Aktualisiert am',
    'watch' => 'Beobachten',
    'unwatch' => 'Nicht mehr beobachten',
    'notify_replies' => 'Bei Antworten benachrichtigen',
    'reply_notification_subject' => 'Neue Antwort in: {title}',
    'reply_notification_body' => '<p>Hallo {username},</p><p>Es gibt eine neue Antwort im Thema <strong>{title}</strong> von <strong>{author}</strong>.</p><p><a href="{link}">Thema anzeigen</a></p>',
    'permissions' => 'Berechtigungen',
    'roles' => 'Rollen',
    'role_name' => 'Rollenname',
    'create_role' => 'Rolle erstellen',
    'edit_role' => 'Rolle bearbeiten',
    'delete_role' => 'Rolle löschen',
    'save_permissions' => 'Berechtigungen speichern',
    'can_approve_threads' => 'Themen genehmigen',
    'can_delete_threads' => 'Themen löschen',
    'can_delete_posts' => 'Beiträge löschen',
    'can_lock_threads' => 'Themen sperren',
    'can_sticky_threads' => 'Themen anheften',
    'can_edit_posts' => 'Beiträge bearbeiten',
    'can_edit_threads' => 'Themen bearbeiten',
    'can_ban_users' => 'Benutzer bannen',
    'can_manage_roles' => 'Rollen verwalten',
    'can_create_threads' => 'Themen erstellen',
    'can_create_posts' => 'Beiträge erstellen',
    'can_edit_own_posts' => 'Eigene Beiträge bearbeiten',
    'can_delete_own_posts' => 'Eigene Beiträge löschen',
    'moderation' => 'Moderation',
    'lock_thread' => 'Thema sperren',
    'unlock_thread' => 'Thema entsperren',
    'sticky_thread' => 'Thema anheften',
    'unsticky_thread' => 'Anheftung aufheben',
    'hide_thread' => 'Thema verstecken',
    'approve_thread' => 'Thema genehmigen',
    'thread_locked' => 'Dieses Thema ist gesperrt. Es können keine neuen Antworten veröffentlicht werden.',
    'user_banned' => 'Dein Account wurde gebannt.',
    'user_suspended' => 'Dein Account wurde vorübergehend suspendiert.',
    'ban_user' => 'Benutzer bannen',
    'unban_user' => 'Benutzer entbannen',
    'status' => 'Status',
    'active' => 'Aktiv',
    'banned' => 'Gebannt',
    'suspended' => 'Suspendiert',
    'send_message' => 'Nachricht senden',

    // --- layout / navigation ---
    'all_discussions' => 'Alle Diskussionen',
    'my_profile' => 'Mein Profil',
    'browse' => 'Durchsuchen',
    'statistics' => 'Statistiken',
    'discussions' => 'Diskussionen',
    'replies' => 'Antworten',
    'views' => 'Aufrufe',
    'posts' => 'Beiträge',
    'members' => 'Mitglieder',
    'contributors' => 'Mitwirkende',
    'newest_member' => 'Neuestes Mitglied',
    'no_categories' => 'Noch keine Kategorien.',
    'join_us' => 'Mitmachen',
    'join_us_text' => 'Erstelle ein Konto, um an den Diskussionen teilzunehmen.',
    'quick_links' => 'Schnelllinks',
    'footer_tagline' => 'Ein leichtgewichtiges, erweiterbares Diskussionsboard.',
    'footer_powered' => 'Powered by PHP & Bootstrap 5',
    'pagination' => 'Seiten',
    'notifications' => 'Benachrichtigungen',
    'messages' => 'Nachrichten',

    // --- discussion listing ---
    'discussions_count' => '{n} Diskussionen',
    'search_results' => 'Suchergebnisse',
    'search_summary' => '{n} Ergebnisse für "{q}"',
    'started_by' => 'Gestartet von',
    'last_activity' => 'Letzte Aktivität',
    'sort_latest' => 'Neueste',
    'sort_replies' => 'Meiste Antworten',
    'sort_views' => 'Meiste Aufrufe',
    'sort_newest' => 'Neueste',
    'sort_oldest' => 'Älteste',
    'sticky' => 'Fixiert',
    'locked' => 'Gesperrt',
    'hidden' => 'Versteckt',

    // --- single discussion ---
    'discussion_info' => 'Diskussion',
    'started' => 'Gestartet',
    'last_reply' => 'Letzte Antwort',
    'published' => 'Veröffentlicht',
    'permalink' => 'Permalink',
    'edit' => 'Bearbeiten',
    'delete' => 'Löschen',
    'edit_post' => 'Beitrag bearbeiten',
    'back_to_first_post' => 'Zurück zum ersten Beitrag',
    'reply_placeholder' => 'Schreibe deine Antwort…',
    'join_conversation' => 'An der Diskussion teilnehmen',
    'join_conversation_text' => 'Erstelle ein kostenloses Konto, um zu antworten, Diskussionen zu verfolgen und Benachrichtigungen zu neuen Antworten zu erhalten.',
    'hide_confirm' => 'Diese Diskussion verstecken?',
    'delete_thread_confirm' => 'Diese Diskussion dauerhaft löschen?',
    'role_admin' => 'Administrator',
    'role_moderator' => 'Moderator',
    'role_member' => 'Mitglied',
    'suspend' => 'Suspendieren',
    'suspend_days' => 'Tage suspendieren:',

    // --- forms ---
    'create_thread_hint' => 'Teile eine Frage, eine Idee oder eine Ankündigung mit der Community.',
    'title_placeholder' => 'Gib deinem Thema einen klaren Titel',
    'edit_profile_hint' => 'Aktualisiere deine Kontodaten und deinen Avatar.',
    'account' => 'Konto',
    'avatar' => 'Avatar',
    'avatar_hint' => 'JPG, PNG, GIF oder WebP. Max 2 MB.',
    'upload_avatar' => 'Avatar hochladen',
    'login_subtitle' => 'Melde dich an, um das Forum zu nutzen.',
    'register_subtitle' => 'Erstelle ein Konto, um an den Diskussionen teilzunehmen.',
    'forgot_subtitle' => 'Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen.',
    'reset_subtitle' => 'Wähle ein neues Passwort für dein Konto.',
    'send_reset_link' => 'Link zum Zurücksetzen senden',
    'back_to_login' => 'Zurück zur Anmeldung',
    'no_account' => 'Noch kein Konto?',
    'have_account' => 'Bereits ein Konto?',
    'new_password' => 'Neues Passwort',
    'confirm_password' => 'Passwort bestätigen',
    'password_min' => 'Mindestens 6 Zeichen.',
    'verify_email' => 'E-Mail bestätigen',
    'verify_email_success' => 'Deine E-Mail-Adresse wurde erfolgreich bestätigt! Du kannst dich jetzt anmelden.',
    'verify_email_invalid' => 'Bestätigungslink ungültig oder abgelaufen.',
    'register_check_email' => 'Bitte überprüfe deine E-Mail, um dein Konto zu bestätigen.',
    'email_not_verified' => 'Bitte bestätige deine E-Mail, bevor du dich anmeldest.',

    // --- relative time ---
    'time_now' => 'gerade eben',
    'time_minute' => 'vor {n} Minute',
    'time_minutes' => 'vor {n} Minuten',
    'time_hour' => 'vor {n} Stunde',
    'time_hours' => 'vor {n} Stunden',
    'time_day' => 'vor {n} Tag',
    'time_days' => 'vor {n} Tagen',
    'time_month' => 'vor {n} Monat',
    'time_months' => 'vor {n} Monaten',
    'time_year' => 'vor {n} Jahr',
    'time_years' => 'vor {n} Jahren',

    // --- admin panel ---
    'admin_panel' => 'Admin-Bereich',
    'dashboard' => 'Dashboard',
    'moderation' => 'Moderation',
    'pending_threads' => 'Ausstehende Themen',
    'management' => 'Verwaltung',
    'categories' => 'Kategorien',
    'users' => 'Benutzer',
    'roles_permissions' => 'Rollen & Berechtigungen',
    'plugins' => 'Plugins',
    'themes' => 'Themes',
    'extensions' => 'Erweiterungen',
    'updates' => 'Aktualisierungen',
    'languages' => 'Sprachen',
    'system' => 'System',
    'settings' => 'Einstellungen',
    'back_to_forum' => 'Zurück zum Forum',
    'language_files' => 'Sprachdateien',
    'diagnostics' => 'Diagnose',
    'system_diagnostics' => 'Systemdiagnose',
    'one_click_install_supported' => 'Die Ein-Klick-Installation von Plugins und Themes aus dem Katalog wird auf diesem Server unterstützt.',
    'one_click_install_may_not_work' => 'Die Ein-Klick-Installation funktioniert möglicherweise nicht. Details siehe unten.',
    'requirements' => 'Anforderungen',
    'check' => 'Prüfung',
    'status' => 'Status',
    'php_version' => 'PHP-Version',
    'zip_extension' => 'PHP-Erweiterung <code>zip</code> (entpackt Pakete)',
    'curl_extension' => 'PHP-Erweiterung <code>curl</code> (lädt Pakete herunter)',
    'allow_url_fopen_setting' => '<code>allow_url_fopen</code> (alternative Herunterladung)',
    'git_optional' => 'Git (optional, wird bei Vorhandensein genutzt)',
    'reach_github_https' => 'GitHub über HTTPS erreichen',
    'recommendations' => 'Empfehlungen',
    'nothing_to_report' => 'Nichts zu melden.',
    'back_to_plugins' => 'Zurück zu den Plugins',
    'site_language_settings' => 'Spracheinstellungen der Seite',
    'default_language' => 'Standardsprache',
    'save_language_settings' => 'Spracheinstellungen speichern',
    'upload_language_file' => 'Sprachdatei hochladen',
    'php_translation_file' => 'PHP-Übersetzungsdatei',
    'installed_languages' => 'Installierte Sprachen',
    'file' => 'Datei',
    'actions' => 'Aktionen',
    'delete' => 'Löschen',
    'default' => 'Standard',
    'install' => 'Installieren',
    'install_from_github' => 'Von GitHub installieren',
    'loading_available_languages' => 'Verfügbare Sprachen werden geladen...',
    'no_languages_found' => 'Keine Sprachen gefunden.',
    'no_language_files_found' => 'Keine Sprachdateien in <code>lang/</code> gefunden.',
    'installed' => 'Installiert',
    'language_code' => 'Sprachcode',
    'code' => 'Code',
    'use_lowercase_letters' => 'Nur Kleinbuchstaben verwenden (z. B. fr, de, es, pt).',
    'file_must_return_array' => 'Die Datei muss ein Array von Schlüssel => übersetzter Zeichenfolge zurückgeben.',
    'unable_to_load_languages' => 'Sprachen konnten nicht von GitHub geladen werden.',
    'failed_to_load_languages' => 'Laden der Sprachen von GitHub fehlgeschlagen.',
    'discussion_info' => 'Diskussion',
    'replies_count' => '{n} Antworten',
    'views_count' => '{n} Aufrufe',
    'members_count' => '{n} Mitglieder',
    'newest_member_label' => 'Neuestes Mitglied',
    'search_results' => 'Suchergebnisse',
    'search_summary' => '{n} Ergebnisse für "{q}"',
    'started_by' => 'Gestartet von',
    'last_activity' => 'Letzte Aktivität',
    'sort_latest' => 'Neueste',
    'sort_replies' => 'Meiste Antworten',
    'sort_views' => 'Meiste Aufrufe',
    'sort_newest' => 'Neueste',
    'sort_oldest' => 'Älteste',
    'sticky' => 'Fixiert',
    'locked' => 'Gesperrt',
    'hidden' => 'Versteckt',
    'started' => 'Gestartet',
    'last_reply' => 'Letzte Antwort',
    'published' => 'Veröffentlicht',
    'permalink' => 'Permalink',
    'edit' => 'Bearbeiten',
    'delete' => 'Löschen',
    'edit_post' => 'Beitrag bearbeiten',
    'back_to_first_post' => 'Zum ersten Beitrag zurückkehren',
    'reply_placeholder' => 'Schreibe deine Antwort…',
    'join_conversation' => 'An der Diskussion teilnehmen',
    'join_conversation_text' => 'Erstelle ein kostenloses Konto, um zu antworten, Diskussionen zu verfolgen und Benachrichtigungen zu neuen Antworten zu erhalten.',
    'hide_confirm' => 'Diese Diskussion verstecken?',
    'delete_thread_confirm' => 'Diese Diskussion dauerhaft löschen?',
    'role_admin' => 'Administrator',
    'role_moderator' => 'Moderator',
    'role_member' => 'Mitglied',
    'suspend' => 'Suspendieren',
    'suspend_days' => 'Tage suspendieren:',

    // --- forms ---
    'create_thread_hint' => 'Teile eine Frage, eine Idee oder eine Ankündigung mit der Community.',
    'title_placeholder' => 'Gib deinem Thema einen klaren Titel',
    'edit_profile_hint' => 'Aktualisiere deine Kontodaten und deinen Avatar.',
    'account' => 'Konto',
    'avatar' => 'Avatar',
    'avatar_hint' => 'JPG, PNG, GIF oder WebP. Max 2 MB.',
    'upload_avatar' => 'Avatar hochladen',
    'login_subtitle' => 'Melde dich an, um das Forum zu nutzen.',
    'register_subtitle' => 'Erstelle ein Konto, um an den Diskussionen teilzunehmen.',
    'forgot_subtitle' => 'Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen.',
    'reset_subtitle' => 'Wähle ein neues Passwort für dein Konto.',
    'send_reset_link' => 'Link zum Zurücksetzen senden',
    'back_to_login' => 'Zurück zur Anmeldung',
    'no_account' => 'Noch kein Konto?',
    'have_account' => 'Bereits ein Konto?',
    'new_password' => 'Neues Passwort',
    'confirm_password' => 'Passwort bestätigen',
    'password_min' => 'Mindestens 6 Zeichen.',
    'verify_email' => 'E-Mail bestätigen',
    'verify_email_success' => 'Deine E-Mail-Adresse wurde erfolgreich bestätigt! Du kannst dich jetzt anmelden.',
    'verify_email_invalid' => 'Bestätigungslink ungültig oder abgelaufen.',
    'register_check_email' => 'Bitte überprüfe deine E-Mail, um dein Konto zu bestätigen.',
    'email_not_verified' => 'Bitte bestätige deine E-Mail, bevor du dich anmeldest.',

    // --- admin settings ---
    'site_settings' => 'Website-Einstellungen',
    'site_tagline' => 'Website-Untertitel',
    'site_icon' => 'Website-Icon',
    'site_icon_hint' => 'Pfad oder URL des Website-Icons.',
    'timezone' => 'Zeitzone',
    'date_format' => 'Datumsformat',
    'time_format' => 'Zeitformat',
    'allow_registration' => 'Registrierung erlauben',
    'maintenance_mode' => 'Wartungsmodus',
    'save_settings' => 'Einstellungen speichern',

    // --- admin tables ---
    'id' => 'ID',
    'name' => 'Name',
    'description' => 'Beschreibung',
    'position' => 'Position',
    'version' => 'Version',

    // --- admin categories ---
    'categories_management' => 'Kategorien verwalten',
    'forum_categories' => 'Forum-Kategorien',
    'add_new_category' => 'Neue Kategorie hinzufügen',
    'add_category' => 'Kategorie hinzufügen',

    // --- admin users ---
    'users_management' => 'Benutzer verwalten',
    'create_user' => 'Benutzer erstellen',
    'role' => 'Rolle',
    'role_user' => 'Benutzer',
    'registered' => 'Registriert',
    'verified' => 'Verifiziert',
    'add_user' => 'Benutzer hinzufügen',
    'left' => 'übrig',

    // --- admin user edit ---
    'edit_user' => 'Benutzer bearbeiten',
    'back_to_users' => 'Zurück zu Benutzern',

    // --- admin roles ---
    'no_permissions' => 'Keine Berechtigungen',
    'permissions_for' => 'Berechtigungen für',
    'role_edit_placeholder' => 'z.B. editor',

    // --- admin plugins ---
    'plugin_manager' => 'Plugin-Verwaltung',
    'install_plugin' => 'Plugin installieren',
    'zip_package' => 'ZIP-Paket',
    'installed_plugins' => 'Installierte Plugins',
    'no_plugins_installed' => 'Keine Plugins installiert. Legen Sie PHP-Plugin-Dateien im Verzeichnis <code>plugins/</code> ab oder laden Sie ein ZIP hoch.',
    'enabled' => 'Aktiviert',
    'disabled' => 'Deaktiviert',
    'enable' => 'Aktivieren',
    'disable' => 'Deaktivieren',
    'plugin' => 'Plugin',

    // --- admin themes ---
    'theme_manager' => 'Theme-Verwaltung',
    'select_active_theme' => 'Aktives Theme auswählen',
    'active_theme' => 'Aktives Theme',
    'install_theme' => 'Theme installieren',
    'theme_zip_requirement' => 'Das ZIP muss einen Ordner mit <code>style.css</code> und optional <code>manifest.json</code> enthalten.',
    'available_themes' => 'Verfügbare Themes',
    'no_themes_found' => 'Keine Themes gefunden. Legen Sie Theme-Ordner im Verzeichnis <code>themes/</code> ab oder laden Sie ein ZIP hoch.',
    'inactive' => 'Inaktiv',
    'activate' => 'Aktivieren',
    'theme' => 'Theme',

    // --- admin moderation ---
    'moderation_queue' => 'Moderationswarteschlange',
    'no_pending_threads' => 'Keine ausstehenden Themen zur Moderation.',
    'author' => 'Autor',
    'date' => 'Datum',
    'unknown' => 'Unbekannt',
    'approve' => 'Genehmigen',

    // --- admin catalog ---
    'catalog' => 'Katalog',
    'browse_catalog' => 'Katalog durchsuchen',
    'search_catalog' => 'Katalog durchsuchen...',
    'available_items' => 'Verfügbare Elemente',
    'no_items_in_catalog' => 'Keine Elemente im Katalog.',
    'not_installed' => 'Nicht installiert',
    'official' => 'Offiziell',
    'type' => 'Typ',

    // --- admin updates ---
    'update_manager' => 'Update-Verwaltung',
    'check_for_updates' => 'Nach Updates suchen',
    'update_status' => 'Update-Status',
    'update_available' => 'Update verfügbar',
    'up_to_date' => 'Aktuell',
    'tracked' => 'Verfolgt',
    'updates_count' => '{n} Updates',
    'all_up_to_date' => 'Alles aktuell',
    'available_updates' => 'Verfügbare Updates',
    'component' => 'Komponente',
    'type' => 'Typ',
    'remote' => 'Remote',
    'apply' => 'Anwenden',
    'apply_update' => 'Update anwenden',
    'all_components_up_to_date' => 'Alle Komponenten sind aktuell.',
    'no_update_info' => 'Keine Update-Informationen verfügbar',
    'update_info_hint' => 'Klicken Sie auf "Nach Updates suchen", um verfügbare Updates für Core, Plugins und Themes zu überprüfen.',
    'from_the' => 'aus',
    'repository' => 'Repository',
    'lang_code_example' => 'z.B. it, en, fr',
    'days' => 'Tage',
];
