<?php
return [
    'site_name' => 'bulletinbored',
    'home' => 'Accueil',
    'login' => 'Connexion',
    'logout' => 'Déconnexion',
    'register' => 'Inscription',
    'username' => 'Nom d\'utilisateur',
    'password' => 'Mot de passe',
    'email' => 'E-mail',
    'new_thread' => 'Nouvelle discussion',
    'create_thread' => 'Créer une nouvelle discussion',
    'reply' => 'Répondre',
    'submit_reply' => 'Envoyer la réponse',
    'edit_profile' => 'Modifier le profil',
    'save_changes' => 'Enregistrer les modifications',
    'profile' => 'Profil',
    'joined' => 'Inscrit depuis',
    'threads_by' => 'Discussions de',
    'no_threads' => 'Aucune discussion pour le moment.',
    'no_replies' => 'Aucune réponse pour le moment.',
    'login_required' => 'Connexion requise',
    'invalid_credentials' => 'Identifiants invalides',
    'welcome' => 'Bienvenue',
    'password_reset_request' => 'Demande de réinitialisation du mot de passe',
    'password_reset_success' => 'Réinitialisation du mot de passe réussie',
    'search' => 'Rechercher',
    'categories' => 'Catégories',
    'recent_threads' => 'Discussions récentes',
    'category' => 'Catégorie',
    'admin_panel' => 'Panneau d\'administration',
    'admin_required' => 'Administrateur requis',
    'settings_saved' => 'Paramètres enregistrés avec succès',
    'thread_not_found' => 'Discussion non trouvée',
    'post_not_found' => 'Message non trouvé',
    'delete_confirm' => 'Supprimer ?',
    'cancel' => 'Annuler',
    'attachments' => 'Pièces jointes',
    'optional' => 'Optionnel',
    'leave_blank_keep' => 'Laisser vide pour conserver l\'actuel',
    'title' => 'Titre',
    'content' => 'Contenu',
    'created_at' => 'Créé le',
    'updated_at' => 'Mis à jour le',
    'watch' => 'Suivre',
    'unwatch' => 'Ne plus suivre',
    'notify_replies' => 'Me notifier des réponses',
    'reply_notification_subject' => 'Nouvelle réponse dans : {title}',
    'reply_notification_body' => '<p>Bonjour {username},</p><p>Il y a une nouvelle réponse dans la discussion <strong>{title}</strong> de <strong>{author}</strong>.</p><p><a href="{link}">Voir la discussion</a></p>',
    'permissions' => 'Permissions',
    'roles' => 'Rôles',
    'role_name' => 'Nom du rôle',
    'create_role' => 'Créer un rôle',
    'edit_role' => 'Modifier le rôle',
    'delete_role' => 'Supprimer le rôle',
    'save_permissions' => 'Enregistrer les permissions',
    'can_approve_threads' => 'Approuver les discussions',
    'can_delete_threads' => 'Supprimer les discussions',
    'can_delete_posts' => 'Supprimer les messages',
    'can_lock_threads' => 'Verrouiller les discussions',
    'can_sticky_threads' => 'Épingler les discussions',
    'can_edit_posts' => 'Modifier les messages',
    'can_edit_threads' => 'Modifier les discussions',
    'can_ban_users' => 'Bannir des utilisateurs',
    'can_manage_roles' => 'Gérer les rôles',
    'can_create_threads' => 'Créer des discussions',
    'can_create_posts' => 'Créer des messages',
    'can_edit_own_posts' => 'Modifier ses propres messages',
    'can_delete_own_posts' => 'Supprimer ses propres messages',
    'moderation' => 'Modération',
    'lock_thread' => 'Verrouiller la discussion',
    'unlock_thread' => 'Déverrouiller la discussion',
    'sticky_thread' => 'Épingler la discussion',
    'unsticky_thread' => 'Désépingler la discussion',
    'hide_thread' => 'Masquer la discussion',
    'approve_thread' => 'Approuver la discussion',
    'thread_locked' => 'Cette discussion est verrouillée. Aucune nouvelle réponse ne peut être publiée.',
    'user_banned' => 'Votre compte a été banni.',
    'user_suspended' => 'Votre compte a été temporairement suspendu.',
    'ban_user' => 'Bannir l\'utilisateur',
    'unban_user' => 'Réactiver l\'utilisateur',
    'status' => 'Statut',
    'active' => 'Actif',
    'banned' => 'Banni',
    'suspended' => 'Suspendu',
    'send_message' => 'Envoyer un message',

    // --- layout / navigation ---
    'all_discussions' => 'Toutes les discussions',
    'my_profile' => 'Mon profil',
    'browse' => 'Parcourir',
    'statistics' => 'Statistiques',
    'discussions' => 'Discussions',
    'replies' => 'Réponses',
    'views' => 'Vues',
    'posts' => 'Messages',
    'members' => 'Membres',
    'contributors' => 'Contributeurs',
    'newest_member' => 'Nouveau membre',
    'no_categories' => 'Aucune catégorie pour le moment.',
    'join_us' => 'Rejoignez-nous',
    'join_us_text' => 'Créez un compte pour participer aux discussions.',
    'quick_links' => 'Liens rapides',
    'footer_tagline' => 'Une plateforme de discussion légère et extensible.',
    'footer_powered' => 'Powered by PHP & Bootstrap 5',
    'pagination' => 'Pagination',
    'notifications' => 'Notifications',
    'messages' => 'Messages',

    // --- discussion listing ---
    'discussions_count' => '{n} discussions',
    'search_results' => 'Résultats de recherche',
    'search_summary' => '{n} résultats pour "{q}"',
    'started_by' => 'Démarrée par',
    'last_activity' => 'Dernière activité',
    'sort_latest' => 'Plus récentes',
    'sort_replies' => 'Plus de réponses',
    'sort_views' => 'Plus vues',
    'sort_newest' => 'Plus récentes',
    'sort_oldest' => 'Plus anciennes',
    'sticky' => 'Épinglée',
    'locked' => 'Verrouillée',
    'hidden' => 'Masquée',

    // --- single discussion ---
    'discussion_info' => 'Discussion',
    'started' => 'Démarrée',
    'last_reply' => 'Dernière réponse',
    'published' => 'Publiée',
    'permalink' => 'Lien permanent',
    'edit' => 'Modifier',
    'delete' => 'Supprimer',
    'edit_post' => 'Modifier le message',
    'back_to_first_post' => 'Retour au premier message',
    'reply_placeholder' => 'Écrivez votre réponse…',
    'join_conversation' => 'Rejoindre la conversation',
    'join_conversation_text' => 'Créez un compte gratuit pour répondre, suivre les discussions et être notifié des nouvelles réponses.',
    'hide_confirm' => 'Masquer cette discussion ?',
    'delete_thread_confirm' => 'Supprimer cette discussion définitivement ?',
    'role_admin' => 'Administrateur',
    'role_moderator' => 'Modérateur',
    'role_member' => 'Membre',
    'suspend' => 'Suspendre',
    'suspend_days' => 'Jours de suspension :',

    // --- forms ---
    'create_thread_hint' => 'Partagez une question, une idée ou une annonce avec la communauté.',
    'title_placeholder' => 'Donnez un titre clair à votre discussion',
    'edit_profile_hint' => 'Mettez à jour les informations de votre compte et votre avatar.',
    'account' => 'Compte',
    'avatar' => 'Avatar',
    'avatar_hint' => 'JPG, PNG, GIF ou WebP. Maximum 2 MB.',
    'upload_avatar' => 'Télécharger un avatar',
    'login_subtitle' => 'Connectez-vous pour continuer sur le forum.',
    'register_subtitle' => 'Créez un compte pour participer aux discussions.',
    'forgot_subtitle' => 'Entrez votre e-mail et nous vous enverrons un lien de réinitialisation.',
    'reset_subtitle' => 'Choisissez un nouveau mot de passe pour votre compte.',
    'send_reset_link' => 'Envoyer le lien de réinitialisation',
    'back_to_login' => 'Retour à la connexion',
    'no_account' => 'Vous n\'avez pas de compte ?',
    'have_account' => 'Vous avez déjà un compte ?',
    'new_password' => 'Nouveau mot de passe',
    'confirm_password' => 'Confirmer le mot de passe',
    'password_min' => 'Minimum 6 caractères.',
    'verify_email' => 'Vérifier l\'e-mail',
    'verify_email_success' => 'Votre e-mail a été vérifié avec succès! Vous pouvez maintenant vous connecter.',
    'verify_email_invalid' => 'Lien de vérification invalide ou expiré.',
    'register_check_email' => 'Veuillez vérifier votre e-mail pour confirmer votre compte.',
    'email_not_verified' => 'Veuillez vérifier votre e-mail avant de vous connecter.',

    // --- relative time ---
    'time_now' => 'à l\'instant',
    'time_minute' => 'Il y a {n} minute',
    'time_minutes' => 'Il y a {n} minutes',
    'time_hour' => 'Il y a {n} heure',
    'time_hours' => 'Il y a {n} heures',
    'time_day' => 'Il y a {n} jour',
    'time_days' => 'Il y a {n} jours',
    'time_month' => 'Il y a {n} mois',
    'time_months' => 'Il y a {n} mois',
    'time_year' => 'Il y a {n} an',
    'time_years' => 'Il y a {n} ans',

    // --- admin panel ---
    'admin_panel' => 'Panneau d\'administration',
    'dashboard' => 'Tableau de bord',
    'moderation' => 'Modération',
    'pending_threads' => 'Discussions en attente',
    'management' => 'Gestion',
    'categories' => 'Catégories',
    'users' => 'Utilisateurs',
    'roles_permissions' => 'Rôles et permissions',
    'plugins' => 'Plugins',
    'themes' => 'Thèmes',
    'extensions' => 'Extensions',
    'updates' => 'Mises à jour',
    'languages' => 'Langues',
    'system' => 'Système',
    'settings' => 'Paramètres',
    'back_to_forum' => 'Retour au forum',
    'language_files' => 'Fichiers de langue',
    'site_language_settings' => 'Paramètres de langue du site',
    'default_language' => 'Langue par défaut',
    'save_language_settings' => 'Enregistrer les paramètres de langue',
    'upload_language_file' => 'Télécharger un fichier de langue',
    'php_translation_file' => 'Fichier de traduction PHP',
    'installed_languages' => 'Langues installées',
    'file' => 'Fichier',
    'actions' => 'Actions',
    'delete' => 'Supprimer',
    'default' => 'Par défaut',
    'install' => 'Installer',
    'install_from_github' => 'Installer depuis GitHub',
    'loading_available_languages' => 'Chargement des langues disponibles...',
    'no_languages_found' => 'Aucune langue trouvée.',
    'no_language_files_found' => 'Aucun fichier de langue trouvé dans <code>lang/</code>.',
    'installed' => 'Installée',
    'language_code' => 'Code de langue',
    'code' => 'Code',
    'use_lowercase_letters' => 'Utilisez uniquement des lettres minuscules (ex. fr, de, es, pt).',
    'file_must_return_array' => 'Le fichier doit retourner un tableau de clé => chaîne traduite.',
    'unable_to_load_languages' => 'Impossible de charger les langues depuis GitHub.',
    'failed_to_load_languages' => 'Échec du chargement des langues depuis GitHub.',
    'discussion_info' => 'Discussion',
    'replies_count' => '{n} réponses',
    'views_count' => '{n} vues',
    'members_count' => '{n} membres',
    'newest_member_label' => 'Nouveau membre',
    'search_results' => 'Résultats de recherche',
    'search_summary' => '{n} résultats pour "{q}"',
    'started_by' => 'Démarrée par',
    'last_activity' => 'Dernière activité',
    'sort_latest' => 'Plus récentes',
    'sort_replies' => 'Plus de réponses',
    'sort_views' => 'Plus vues',
    'sort_newest' => 'Plus récentes',
    'sort_oldest' => 'Plus anciennes',
    'sticky' => 'Épinglée',
    'locked' => 'Verrouillée',
    'hidden' => 'Masquée',
    'started' => 'Démarrée',
    'last_reply' => 'Dernière réponse',
    'published' => 'Publiée',
    'permalink' => 'Lien permanent',
    'edit' => 'Modifier',
    'delete' => 'Supprimer',
    'edit_post' => 'Modifier le message',
    'back_to_first_post' => 'Retour au premier message',
    'reply_placeholder' => 'Écrivez votre réponse…',
    'join_conversation' => 'Rejoindre la conversation',
    'join_conversation_text' => 'Créez un compte gratuit pour répondre, suivre les discussions et être notifié des nouvelles réponses.',
    'hide_confirm' => 'Masquer cette discussion ?',
    'delete_thread_confirm' => 'Supprimer cette discussion définitivement ?',
    'role_admin' => 'Administrateur',
    'role_moderator' => 'Modérateur',
    'role_member' => 'Membre',
    'suspend' => 'Suspendre',
    'suspend_days' => 'Jours de suspension :',
    'create_thread_hint' => 'Partagez une question, une idée ou une annonce avec la communauté.',
    'title_placeholder' => 'Donnez un titre clair à votre discussion',
    'edit_profile_hint' => 'Mettez à jour les informations de votre compte et votre avatar.',
    'account' => 'Compte',
    'avatar' => 'Avatar',
    'avatar_hint' => 'JPG, PNG, GIF ou WebP. Maximum 2 MB.',
    'upload_avatar' => 'Télécharger un avatar',
    'login_subtitle' => 'Connectez-vous pour continuer sur le forum.',
    'register_subtitle' => 'Créez un compte pour participer aux discussions.',
    'forgot_subtitle' => 'Entrez votre e-mail et nous vous enverrons un lien de réinitialisation.',
    'reset_subtitle' => 'Choisissez un nouveau mot de passe pour votre compte.',
    'send_reset_link' => 'Envoyer le lien de réinitialisation',
    'back_to_login' => 'Retour à la connexion',
    'no_account' => 'Vous n\'avez pas de compte ?',
    'have_account' => 'Vous avez déjà un compte ?',
    'new_password' => 'Nouveau mot de passe',
    'confirm_password' => 'Confirmer le mot de passe',
    'password_min' => 'Minimum 6 caractères.',
    'verify_email' => 'Vérifier l\'e-mail',
    'verify_email_success' => 'Votre e-mail a été vérifié avec succès! Vous pouvez maintenant vous connecter.',
    'verify_email_invalid' => 'Lien de vérification invalide ou expiré.',
    'register_check_email' => 'Veuillez vérifier votre e-mail pour confirmer votre compte.',
    'email_not_verified' => 'Veuillez vérifier votre e-mail avant de vous connecter.',

    // --- admin settings ---
    'site_settings' => 'Paramètres du site',
    'site_tagline' => 'Slogan du site',
    'site_icon' => 'Icône du site',
    'site_icon_hint' => 'Chemin ou URL de l\'image de l\'icône du site.',
    'timezone' => 'Fuseau horaire',
    'date_format' => 'Format de date',
    'time_format' => 'Format d\'heure',
    'allow_registration' => 'Autoriser l\'inscription',
    'maintenance_mode' => 'Mode maintenance',
    'save_settings' => 'Enregistrer les paramètres',

    // --- admin tables ---
    'id' => 'ID',
    'name' => 'Nom',
    'description' => 'Description',
    'position' => 'Position',
    'version' => 'Version',

    // --- admin categories ---
    'categories_management' => 'Gestion des catégories',
    'forum_categories' => 'Catégories du forum',
    'add_new_category' => 'Ajouter une nouvelle catégorie',
    'add_category' => 'Ajouter une catégorie',

    // --- admin users ---
    'users_management' => 'Gestion des utilisateurs',
    'create_user' => 'Créer un utilisateur',
    'role' => 'Rôle',
    'role_user' => 'Utilisateur',
    'registered' => 'Inscrit',
    'verified' => 'Vérifié',
    'add_user' => 'Ajouter un utilisateur',
    'left' => 'restants',

    // --- admin user edit ---
    'edit_user' => 'Modifier l\'utilisateur',
    'back_to_users' => 'Retour aux utilisateurs',

    // --- admin roles ---
    'no_permissions' => 'Aucune permission',
    'permissions_for' => 'Permissions pour',
    'role_edit_placeholder' => 'ex. éditeur',

    // --- admin plugins ---
    'plugin_manager' => 'Gestion des plugins',
    'install_plugin' => 'Installer un plugin',
    'zip_package' => 'Archive ZIP',
    'installed_plugins' => 'Plugins installés',
    'no_plugins_installed' => 'Aucun plugin installé. Placez les fichiers PHP des plugins dans le répertoire <code>plugins/</code> ou téléchargez une archive ZIP.',
    'enabled' => 'Activé',
    'disabled' => 'Désactivé',
    'enable' => 'Activer',
    'disable' => 'Désactiver',
    'plugin' => 'Plugin',

    // --- admin themes ---
    'theme_manager' => 'Gestion des thèmes',
    'select_active_theme' => 'Sélectionner le thème actif',
    'active_theme' => 'Thème actif',
    'install_theme' => 'Installer un thème',
    'theme_zip_requirement' => 'L\'archive ZIP doit contenir un dossier avec <code>style.css</code> et <code>manifest.json</code> optionnel.',
    'available_themes' => 'Thèmes disponibles',
    'no_themes_found' => 'Aucun thème trouvé. Placez les dossiers de thèmes dans le répertoire <code>themes/</code> ou téléchargez une archive ZIP.',
    'inactive' => 'Inactif',
    'activate' => 'Activer',
    'theme' => 'Thème',

    // --- admin moderation ---
    'moderation_queue' => 'File de modération',
    'no_pending_threads' => 'Aucune discussion en attente de modération.',
    'author' => 'Auteur',
    'date' => 'Date',
    'unknown' => 'Inconnu',
    'approve' => 'Approuver',

    // --- admin catalog ---
    'catalog' => 'Catalogue',
    'browse_catalog' => 'Parcourir le catalogue',
    'search_catalog' => 'Rechercher dans le catalogue...',
    'available_items' => 'Éléments disponibles',
    'no_items_in_catalog' => 'Aucun élément dans le catalogue.',
    'not_installed' => 'Non installé',
    'official' => 'Officiel',
    'type' => 'Type',

    // --- admin updates ---
    'update_manager' => 'Gestion des mises à jour',
    'check_for_updates' => 'Rechercher des mises à jour',
    'update_status' => 'État des mises à jour',
    'update_available' => 'Mise à jour disponible',
    'up_to_date' => 'À jour',
    'tracked' => 'Suivis',
    'updates_count' => '{n} mises à jour',
    'all_up_to_date' => 'Tout est à jour',
    'available_updates' => 'Mises à jour disponibles',
    'component' => 'Composant',
    'type' => 'Type',
    'remote' => 'Distant',
    'apply' => 'Appliquer',
    'apply_update' => 'Appliquer la mise à jour',
    'all_components_up_to_date' => 'Tous les composants sont à jour.',
    'no_update_info' => 'Aucune information de mise à jour disponible',
    'update_info_hint' => 'Cliquez sur "Rechercher des mises à jour" pour vérifier les mises à jour disponibles pour le cœur, les plugins et les thèmes.',
    'from_the' => 'depuis',
    'repository' => 'dépôt',
    'lang_code_example' => 'ex. it, en, fr',
    'days' => 'Jours',
];
